### ISSUE TITLE
Can this verification be used for verification of World of Warcraft servers?

### ISSUE THREAD

**Issue by fan3750060** [simbo1905/thinbus-srp-npm#10]
Can this verification be used for verification of World of Warcraft servers?

**Comment by simbo1905** [comment]
What verification of, or to, WoW servers is required? This is a zero-knowledge authentication library. It allows someone or something to verify itself to a server without a shared secret, or public key cryto. RFC5054 uses it in TLS for machine to machine security. There are other methods of programs to verify themselves to one another (public key crypto, mTLS with certificates).  This technique is optimised to make it easy for people to use as they only need to memorise a password or passphrase. In theory any service can use it. Any service that is using passwords would be made more secure by upgrading to the SRP protocol. I will close this question as it is very open ended but feel free to continue the discussion.
