### ISSUE TITLE
Make a version 2.0 that’s Typescript FP

### ISSUE THREAD

**Issue by simbo1905** [simbo1905/thinbus-srp-npm#3]
The current implementation follows the old school OO style of Nimbus the Java library. An upgrade to functional programming and TypeScript would be a big simplification.

**Comment by bufistov** [comment]
Hi there,

We tried to do it here [tssrp6a](https://github.com/midonet/tssrp6a)
Welcome :)

**Comment by amostech** [comment]
BUMP! This a great library that we would like to have at least a typings library for. index.d.ts for example would solve our issue. The library doesn't have to be re-written to be compatible.

**Comment by simbo1905** [comment]
Types are so that you can have strong confidence in the contract. Yet with a crypto verification library, there is minimal data to exchange, that is just a couple of strings. With such a small interface, I am not convinced that doing anything other than lowest common denominator JS pays its way. 

Regardless this issue was not about adding types. There was another issue for that task that is also closed. Instead, this issue was about the OO-ness of classes and methods. The design has the engineer instantiate a class just to call one method. Now that I am more experienced I think that's bad fit; a wire protocol is far better modelled as functional. 

Changing this software to have a completely different functional model rather than an OO model would be a very disruptive breaking change. Rather than do that I would prefer to leave this as-is and if i had the time start a new JS+TS project. 

So I will close this issue as won't fix.
